version: '3.8'
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test usePageObjects.spec.ts --project=chromium
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results:/app/test-results
